### ISSUE TITLE
Where to use the permission power shell scripts?

### ISSUE THREAD

**Issue by dustojnikhummer** [CoasterKaty/PHPGraphMailer#10]
I'm trying to find a way to access my Exchange inbox with php as an application. Of course i don't want the app to have access to my entire organization, but I don't know where to use those powershell scripts you mention in your doc

<code> New-ApplicationAccessPolicy -AppId clientID -PolicyScopeGroupId mailbox@domain.com -AccessRight RestrictAccess </code>

Is that for the Azure Cloud Shell that is in portal.azure.com? Because I can't use that, no Azure subscription.

**Comment by CoasterKaty** [comment]
In a normal Exchange Online powershell window, doesn't have to be in the Azure Cloud Shell.
