### ISSUE TITLE
SentItems

### ISSUE THREAD

**Issue by oliphil** [CoasterKaty/PHPGraphMailer#15]
Hello,

Everything works fine to send email however, I can't see any of the sent items in the folder "sent" in spite the fact that I set false in 

`$graphMailer->sendMail('my@email.com', $mailArgs, 'false');`

Any hint ?

**Comment by CoasterKaty** [comment]
You need to pass the Boolean false, not a string containing the word “false”, ie

$graphMailer->sendMail('my@email.com', $mailArgs, false);

that should then skip the deletion of the item from sent items.

**Comment by oliphil** [comment]
OMG !  Now I'm embarrassed just for asking !

Thank you !
