### ISSUE TITLE
Question: How to know the mailbox name?

### ISSUE THREAD

**Issue by ngekoding** [CoasterKaty/PHPGraphMailer#2]
Sorry for asking some basic question, but I don't know where to find the `mailbox` for the parameter?
Like when getting the messages, it required the `mailbox param`.

Any guide for that? I am new to Azure.

Thanks in advance

**Comment by CoasterKaty** [comment]
That would be the email address of the mailbox you want to read/send from, which would need to be an Office 365 account which you have delegated permission to your application to read, as per the instructions on https://katystech.blog/projects/php-graph-mailer

e.g.

```php
$messages = $graphMailer->getMessages('helpdesk@contoso.com');
echo '<pre>';
print_r($messages);
echo '</pre>';```

**Comment by ngekoding** [comment]
Thank you, problem was solved.
