### ISSUE TITLE
syntax error, unexpected '->' (T_OBJECT_OPERATOR)

### ISSUE THREAD

**Issue by ghostmaster75** [CoasterKaty/PHPGraphMailer#3]
hi,
i have this issue:

`Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /inc/graph_mailer.php on line 43`

PHP Version 5.5.9-1

**Comment by CoasterKaty** [comment]
Maybe that directly accessing value without first assigning to a variable is not supported by that version of PHP as it was written for PHP7. Try changing line 43 from:

$attachments = (json_decode($this->sendGetRequest($this->baseURL . 'users/' . $mailbox . '/messages/' . $mailItem->id . '/attachments')))->value;

to:

$attachmentObj = json_decode($this->sendGetRequest($this->baseURL . 'users/' . $mailbox . '/messages/' . $mailItem->id . '/attachments'));
$attachments = $attachmentObj->value;

and see if that fixes it
